version: '3.6'

services:
  mongodb:
    image: mongo:4.4.6
    container_name: 'movieology-db'
    volumes:
      - "./_databases:/data/db"
    ports:
      - 27017:27017
    command: mongod
